import pygame
pygame.init()

INFO = pygame.display.Info()
MONITOR_HEIGHT = INFO.current_h

SQUARE_LENGTH = MONITOR_HEIGHT // 2

FPS = 60

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0, 127)
CADET_BLUE = (152, 255, 255)
WINNER_FONT = pygame.font.SysFont('comicsans', SQUARE_LENGTH // 10)
DRAW_FONT = pygame.font.SysFont('comicsans', SQUARE_LENGTH // 10)

GRID_VERT_WIDTH = SQUARE_LENGTH / 300 # Used in big grid
GRID_HORIZ_HEIGHT = SQUARE_LENGTH / 300
LETTER_LENGTH = (SQUARE_LENGTH - 2 * GRID_VERT_WIDTH) / 3 # since 3*LETTER_LENGTH + 2*GRID_VERT_WIDTH = SQUARE_LENGTH
GRID_VERT_WIDTH_SUB = SQUARE_LENGTH / 600 # Used in sub-grids
GRID_HORIZ_HEIGHT_SUB = SQUARE_LENGTH / 600
LETTER_LENGTH_SUB = (LETTER_LENGTH - 2 * GRID_VERT_WIDTH_SUB) / 3 # since 3*LETTER_LENGTH_SUB + 2*GRID_VERT_WIDTH_SUB = LETTER_LENGTH

LETTER_X_IMAGE = pygame.image.load("images/letter_x_image.png")
LETTER_X_IMAGE_BLUE = pygame.image.load("images/letter_x_image_blue.png")
LETTER_X = pygame.transform.scale(LETTER_X_IMAGE_BLUE, (int(round(LETTER_LENGTH)), int(round(LETTER_LENGTH)))) # Used in big grid
LETTER_X_SUB = pygame.transform.scale(LETTER_X_IMAGE, (int(round(LETTER_LENGTH_SUB)), int(round(LETTER_LENGTH_SUB)))) # Used in sub-grids
LETTER_O_IMAGE = pygame.image.load("images/letter_o_image.png")
LETTER_O_IMAGE_BLUE = pygame.image.load("images/letter_o_image_blue.png")
LETTER_O = pygame.transform.scale(LETTER_O_IMAGE_BLUE, (int(round(LETTER_LENGTH)), int(round(LETTER_LENGTH))))
LETTER_O_SUB = pygame.transform.scale(LETTER_O_IMAGE, (int(round(LETTER_LENGTH_SUB)), int(round(LETTER_LENGTH_SUB))))

# The following rectangles represent the big vertical and horizontal lines used in the big grid
# Similarly the letter locations and cells are for the big grid

GRID_VERT_1 = pygame.Rect(LETTER_LENGTH, 0, GRID_VERT_WIDTH, SQUARE_LENGTH)
GRID_VERT_2 = pygame.Rect(2 * LETTER_LENGTH + GRID_VERT_WIDTH, 0, GRID_VERT_WIDTH, SQUARE_LENGTH)
GRID_HORIZ_1 = pygame.Rect(0, LETTER_LENGTH, SQUARE_LENGTH, GRID_HORIZ_HEIGHT)
GRID_HORIZ_2 = pygame.Rect(0, 2 * LETTER_LENGTH + GRID_HORIZ_HEIGHT, SQUARE_LENGTH, GRID_HORIZ_HEIGHT)

LETTER_LOCATIONS = [(0, 0), (GRID_VERT_1.right, 0), (GRID_VERT_2.right, 0), (0, GRID_HORIZ_1.bottom), 
                                    (GRID_VERT_1.right, GRID_HORIZ_1.bottom), (GRID_VERT_2.right, GRID_HORIZ_1.bottom), 
                                    (0, GRID_HORIZ_2.bottom), (GRID_VERT_1.right, GRID_HORIZ_2.bottom), (GRID_VERT_2.right, GRID_HORIZ_2.bottom)]

CELLS = [pygame.Rect(item[0], item[1], LETTER_LENGTH, LETTER_LENGTH) for item in LETTER_LOCATIONS] # Represent grid cells as pygame rectangles

# The following rectangles represent the small vertical and horizontal lines of each subgrid. The last two digits ij stand for the j'th vert or horiz within sub-grid i.
# Similarly the letter locations and cells are for the correspoding sub-grid

GRID_VERT_01 = pygame.Rect(LETTER_LENGTH_SUB, 0, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_02 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB, 0, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_01 = pygame.Rect(0, LETTER_LENGTH_SUB, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_02 = pygame.Rect(0, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_0 = [(0, 0), (GRID_VERT_01.right, 0), (GRID_VERT_02.right, 0), (0, GRID_HORIZ_01.bottom), 
                                    (GRID_VERT_01.right, GRID_HORIZ_01.bottom), (GRID_VERT_02.right, GRID_HORIZ_01.bottom), 
                                    (0, GRID_HORIZ_02.bottom), (GRID_VERT_01.right, GRID_HORIZ_02.bottom), (GRID_VERT_02.right, GRID_HORIZ_02.bottom)]

CELLS_0 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_0]

GRID_VERT_11 = pygame.Rect(LETTER_LENGTH_SUB + LETTER_LENGTH + GRID_VERT_WIDTH, 0, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_12 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB + LETTER_LENGTH + GRID_VERT_WIDTH, 0, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_11 = pygame.Rect(LETTER_LENGTH + GRID_VERT_WIDTH, LETTER_LENGTH_SUB, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_12 = pygame.Rect(LETTER_LENGTH + GRID_VERT_WIDTH, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_1 = [(GRID_VERT_1.right, 0), (GRID_VERT_11.right, 0), (GRID_VERT_12.right, 0), (GRID_VERT_1.right, GRID_HORIZ_11.bottom), 
                                    (GRID_VERT_11.right, GRID_HORIZ_11.bottom), (GRID_VERT_12.right, GRID_HORIZ_11.bottom), 
                                    (GRID_VERT_1.right, GRID_HORIZ_12.bottom), (GRID_VERT_11.right, GRID_HORIZ_12.bottom), (GRID_VERT_12.right, GRID_HORIZ_12.bottom)]

CELLS_1 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_1]

GRID_VERT_21 = pygame.Rect(LETTER_LENGTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, 0, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_22 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, 0, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_21 = pygame.Rect(2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, LETTER_LENGTH_SUB, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_22 = pygame.Rect(2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_2 = [(GRID_VERT_2.right, 0), (GRID_VERT_21.right, 0), (GRID_VERT_22.right, 0), (GRID_VERT_2.right, GRID_HORIZ_21.bottom), 
                                    (GRID_VERT_21.right, GRID_HORIZ_21.bottom), (GRID_VERT_22.right, GRID_HORIZ_21.bottom), 
                                    (GRID_VERT_2.right, GRID_HORIZ_22.bottom), (GRID_VERT_21.right, GRID_HORIZ_22.bottom), (GRID_VERT_22.right, GRID_HORIZ_22.bottom)]

CELLS_2 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_2]

GRID_VERT_31 = pygame.Rect(LETTER_LENGTH_SUB, LETTER_LENGTH + GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_32 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB, LETTER_LENGTH + GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_31 = pygame.Rect(0, LETTER_LENGTH_SUB + LETTER_LENGTH + GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_32 = pygame.Rect(0, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB + LETTER_LENGTH + GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_3 = [(0, GRID_HORIZ_1.bottom), (GRID_VERT_31.right, GRID_HORIZ_1.bottom), (GRID_VERT_32.right, GRID_HORIZ_1.bottom), (0, GRID_HORIZ_31.bottom), (GRID_VERT_31.right, GRID_HORIZ_31.bottom), (GRID_VERT_32.right, GRID_HORIZ_31.bottom), (0, GRID_HORIZ_32.bottom), (GRID_VERT_31.right, GRID_HORIZ_32.bottom), (GRID_VERT_32.right, GRID_HORIZ_32.bottom)]

CELLS_3 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_3]

GRID_VERT_41 = pygame.Rect(LETTER_LENGTH_SUB + LETTER_LENGTH + GRID_VERT_WIDTH, LETTER_LENGTH + GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_42 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB + LETTER_LENGTH + GRID_VERT_WIDTH, LETTER_LENGTH + GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_41 = pygame.Rect(LETTER_LENGTH + GRID_VERT_WIDTH, LETTER_LENGTH_SUB + LETTER_LENGTH + GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_42 = pygame.Rect(LETTER_LENGTH + GRID_VERT_WIDTH, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB + LETTER_LENGTH + GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_4 = [(GRID_VERT_1.right, GRID_HORIZ_1.bottom), (GRID_VERT_41.right, GRID_HORIZ_1.bottom), (GRID_VERT_42.right, GRID_HORIZ_1.bottom), (GRID_VERT_1.right, GRID_HORIZ_41.bottom), 
                                    (GRID_VERT_41.right, GRID_HORIZ_41.bottom), (GRID_VERT_42.right, GRID_HORIZ_41.bottom), 
                                    (GRID_VERT_1.right, GRID_HORIZ_42.bottom), (GRID_VERT_41.right, GRID_HORIZ_42.bottom), (GRID_VERT_42.right, GRID_HORIZ_42.bottom)]

CELLS_4 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_4]

GRID_VERT_51 = pygame.Rect(LETTER_LENGTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, LETTER_LENGTH + GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_52 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, LETTER_LENGTH + GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_51 = pygame.Rect(2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, LETTER_LENGTH_SUB + LETTER_LENGTH + GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_52 = pygame.Rect(2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB + LETTER_LENGTH + GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_5 = [(GRID_VERT_2.right, GRID_HORIZ_1.bottom), (GRID_VERT_51.right, GRID_HORIZ_1.bottom), (GRID_VERT_52.right, GRID_HORIZ_1.bottom), (GRID_VERT_2.right, GRID_HORIZ_51.bottom), 
                                    (GRID_VERT_51.right, GRID_HORIZ_51.bottom), (GRID_VERT_52.right, GRID_HORIZ_51.bottom), 
                                    (GRID_VERT_2.right, GRID_HORIZ_52.bottom), (GRID_VERT_51.right, GRID_HORIZ_52.bottom), (GRID_VERT_52.right, GRID_HORIZ_52.bottom)]

CELLS_5 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_5]

GRID_VERT_61 = pygame.Rect(LETTER_LENGTH_SUB, 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_62 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB, 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_61 = pygame.Rect(0, LETTER_LENGTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_62 = pygame.Rect(0, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB + 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_6 = [(0, GRID_HORIZ_2.bottom), (GRID_VERT_61.right, GRID_HORIZ_2.bottom), (GRID_VERT_62.right, GRID_HORIZ_2.bottom), (0, GRID_HORIZ_61.bottom), 
                                    (GRID_VERT_61.right, GRID_HORIZ_61.bottom), (GRID_VERT_62.right, GRID_HORIZ_61.bottom), 
                                    (0, GRID_HORIZ_62.bottom), (GRID_VERT_61.right, GRID_HORIZ_62.bottom), (GRID_VERT_62.right, GRID_HORIZ_62.bottom)]

CELLS_6 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_6]

GRID_VERT_71 = pygame.Rect(LETTER_LENGTH_SUB + LETTER_LENGTH + GRID_VERT_WIDTH, 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_72 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB + LETTER_LENGTH + GRID_VERT_WIDTH, 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_71 = pygame.Rect(LETTER_LENGTH + GRID_VERT_WIDTH, LETTER_LENGTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_72 = pygame.Rect(LETTER_LENGTH + GRID_VERT_WIDTH, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB + 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_7 = [(GRID_VERT_1.right, GRID_HORIZ_2.bottom), (GRID_VERT_71.right, GRID_HORIZ_2.bottom), (GRID_VERT_72.right, GRID_HORIZ_2.bottom), (GRID_VERT_1.right, GRID_HORIZ_71.bottom), 
                                    (GRID_VERT_71.right, GRID_HORIZ_71.bottom), (GRID_VERT_72.right, GRID_HORIZ_71.bottom), 
                                    (GRID_VERT_1.right, GRID_HORIZ_72.bottom), (GRID_VERT_71.right, GRID_HORIZ_72.bottom), (GRID_VERT_72.right, GRID_HORIZ_72.bottom)]

CELLS_7 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_7]

GRID_VERT_81 = pygame.Rect(LETTER_LENGTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_VERT_82 = pygame.Rect(2 * LETTER_LENGTH_SUB + GRID_VERT_WIDTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, GRID_VERT_WIDTH_SUB, LETTER_LENGTH)
GRID_HORIZ_81 = pygame.Rect(2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, LETTER_LENGTH_SUB + 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)
GRID_HORIZ_82 = pygame.Rect(2 * LETTER_LENGTH + 2 * GRID_VERT_WIDTH, 2 * LETTER_LENGTH_SUB + GRID_HORIZ_HEIGHT_SUB + 2 * LETTER_LENGTH + 2 * GRID_HORIZ_HEIGHT, LETTER_LENGTH, GRID_HORIZ_HEIGHT_SUB)

LETTER_LOCATIONS_8 = [(GRID_VERT_2.right, GRID_HORIZ_2.bottom), (GRID_VERT_81.right, GRID_HORIZ_2.bottom), (GRID_VERT_82.right, GRID_HORIZ_2.bottom), (GRID_VERT_2.right, GRID_HORIZ_81.bottom), 
                                    (GRID_VERT_81.right, GRID_HORIZ_81.bottom), (GRID_VERT_82.right, GRID_HORIZ_81.bottom), 
                                    (GRID_VERT_2.right, GRID_HORIZ_82.bottom), (GRID_VERT_81.right, GRID_HORIZ_82.bottom), (GRID_VERT_82.right, GRID_HORIZ_82.bottom)]

CELLS_8 = [pygame.Rect(item[0], item[1], LETTER_LENGTH_SUB, LETTER_LENGTH_SUB) for item in LETTER_LOCATIONS_8]

SUB_GRID_CELLS = [CELLS_0, CELLS_1, CELLS_2, CELLS_3, CELLS_4, CELLS_5, CELLS_6, CELLS_7, CELLS_8]

SUB_GRID_LETTER_LOCATIONS = [LETTER_LOCATIONS_0, LETTER_LOCATIONS_1, LETTER_LOCATIONS_2, LETTER_LOCATIONS_3, LETTER_LOCATIONS_4, LETTER_LOCATIONS_5, LETTER_LOCATIONS_6, LETTER_LOCATIONS_7, LETTER_LOCATIONS_8]

SMALL_GRID_LINES = [GRID_VERT_01, GRID_VERT_02, GRID_HORIZ_01, GRID_HORIZ_02, GRID_VERT_11, GRID_VERT_12, GRID_HORIZ_11, GRID_HORIZ_12, GRID_VERT_21, GRID_VERT_22, GRID_HORIZ_21, GRID_HORIZ_22, GRID_VERT_31, GRID_VERT_32, GRID_HORIZ_31, GRID_HORIZ_32, GRID_VERT_41, GRID_VERT_42, GRID_HORIZ_41, GRID_HORIZ_42, GRID_VERT_51, GRID_VERT_52, GRID_HORIZ_51, GRID_HORIZ_52, GRID_VERT_61, GRID_VERT_62, GRID_HORIZ_61, GRID_HORIZ_62, GRID_VERT_71, GRID_VERT_72, GRID_HORIZ_71, GRID_HORIZ_72, GRID_VERT_81, GRID_VERT_82, GRID_HORIZ_81, GRID_HORIZ_82]